# CronWorker Configuration

# Cron jobs configuration
jobs:
  - name: "hello-world"
    schedule: "*/2 * * * *"  # Run every 2 minutes
    command: "echo"
    args:
      - "Hello, World!"
    enabled: true
